package com.ody.di.database.entities;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents an analysis entity with details about analyzed images and detected objects.
 * The detected objects will be stored in JSON format.
 *
 * @author Debidutt Prasad
 */
@Entity
public class Analysis {

    /**
     * Unique ID for each analysis. It's autogenerated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    public long serialNumber;

    /**
     * Reference or path to the analyzed image.
     */
    @ColumnInfo(name = "image_reference")
    public String imageReference;

    /**
     * Details about the objects detected during the analysis, stored in JSON format.
     */
    @ColumnInfo(name = "detected_objects")
    public String detectedObjects;

}


